
class ComDummy:
    def __init__(self) -> None:
        raise NotImplementedError('This is a dummy class for type hinting only, do not use it')
    
    
    
class PyITypeComp:
    def Bind(self, szName: str, wflags: int = ...): ...
    def BindType(self, szName: str): ...

class ELEMDESC: ...


class FUNCDESC:
    @property
    def memid(self) -> int: ...
    @property
    def scodeArray(self) -> tuple: ...
    @property
    def args(self) -> tuple[ELEMDESC, ...]: ...
    @property
    def funckind(self): ...
    @property
    def invkind(self): ...
    @property
    def callconv(self): ...
    @property
    def cParamsOpt(self): ...
    @property
    def oVft(self): ...
    @property
    def rettype(self) -> ELEMDESC: ...
    @property
    def wFuncFlags(self): ...

class TYPEDESC: ...
class PyIID: ...


class TYPEATTR:
    @property
    def iid(self) -> PyIID: ...
    @property
    def lcid(self): ...
    @property
    def memidConstructor(self): ...
    @property
    def memidDestructor(self): ...
    @property
    def cbSizeInstance(self): ...
    @property
    def typekind(self): ...
    @property
    def cFuncs(self): ...
    @property
    def cVars(self): ...
    @property
    def cImplTypes(self): ...
    @property
    def cbSizeVft(self): ...
    @property
    def cbAlignment(self): ...
    @property
    def wTypeFlags(self): ...
    @property
    def wMajorVerNum(self): ...
    @property
    def wMinorVerNum(self): ...
    @property
    def tdescAlias(self) -> TYPEDESC: ...
    @property
    def idldeskType(self): ...

class TLIBATTR: ...


class VARDESC:
    @property
    def memid(self): ...
    @property
    def value(self): ...
    @property
    def elemdescVar(self) -> ELEMDESC: ...
    @property
    def varFlags(self): ...
    @property
    def varkind(self): ...

class PyITypeInfo:
    def GetContainingTypeLib(self) -> tuple['PyITypeLib']: ...
    def GetDocumentation(self, memberId) -> tuple: ...
    def GetFuncDesc(self, memberId) -> FUNCDESC: ...
    def GetImplTypeFlags(self, index): ...
    def GetIDsOfNames(self): ...
    def GetNames(self, memberId): ...
    def GetTypeAttr(self) -> TYPEATTR: ...
    def GetRefTypeInfo(self, hRefType) -> 'PyITypeInfo': ...
    def GetRefTypeOfImplType(self, hRefType): ...
    def GetVarDesc(self, memberId) -> VARDESC: ...
    def GetTypeComp(self) -> PyITypeComp: ...

class PyITypeLib:
    def GetDocumentation(self, index): ...
    def GetLibAttr(self) -> TLIBATTR: ...
    def GetTypeComp(self) -> PyITypeComp: ...
    def GetTypeInfo(self, index) -> PyITypeInfo: ...
    def GetTypeInfoCount(self): ...
    def GetTypeInfoOfGuid(self, iid: PyIID) -> PyITypeInfo: ...
    def GetTypeInfoType(self, index): ...
